# Generated by Django 4.2.1 on 2023-12-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('email_open', 'Email Open'), ('email_click', 'Email Click'), ('email_unsubscribe', 'Email Unsubscribe'), ('purchase', 'Purchase')], max_length=20)),
                ('event_data', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
